class_name Enum

enum Type {ANY, BATTLE, EVENT, SITUATION}
enum Attribute {ANY, HUMAN, REALIAN, MACHINE, GNOSIS, MONSTER, BLADE, WEAPON, NOPON, UNKNOWN}
enum AttackType {ANY, HAND, BALLISTIC, SPREAD, HOMING, NONE}
enum Rarity {COMMON, UNCOMMON, RARE, PROMO}
enum Zone {NONE, DECK, LOST, JUNK, HAND, STANDBY, SITUATION, BATTLEFIELD}
enum Phase {DRAW, MOVE, EVENT, SET, BLOCK, BATTLE, ADJUST}
